export const buttonData = {
  hero: [],
  faqSection: [],
  sliderAnimation: [],
  animationSection: [],
  carouselAlgo: [],
  companiesWorking: [],
  customerJourney: [],
  desktopFooterSection: [],
  featureSection: [],
  footer: [],
  footerSection: [],
  getJobs: [],
  getStartedSection: [],
  heroSection: [],
  mobileFooterSection: [],
  navbar: [],
  responsiveAnimationSection: [],
  resumeCarousel: [],
  tempelatePage: [],
  testimonialSection: [],
  verticalAnimationSection: [],
};
